# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-10 13:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0007_modify_course_daily_metrics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursedailymetrics',
            options={'ordering': ('-date_for', 'course_id')},
        ),
        migrations.AlterField(
            model_name='coursedailymetrics',
            name='average_progress',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MaxValueValidator(1.0), django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
